//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace OvationTest {
    
    
    public partial class contact {
        
        /// <summary>
        /// OvationRFPMetatags1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OvationTest.OvationControls.OvationRFPMetatags OvationRFPMetatags1;
        
        /// <summary>
        /// OvationCommonCSSJscript1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OvationTest.OvationControls.OvationCommonCSSJscript OvationCommonCSSJscript1;
        
        /// <summary>
        /// contactform control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm contactform;
        
        /// <summary>
        /// OvationRFPGlobalScrptMgr1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OvationTest.OvationControls.OvationRFPGlobalScrptMgr OvationRFPGlobalScrptMgr1;
    }
}
