<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="RFPadmin.aspx.cs" Inherits="OvationTest.RFPadmin" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <telerik:RadScriptManager ID="RadScriptManager1" Runat="server">
        </telerik:RadScriptManager>
    <telerik:RadGrid ID="RadGrid1" runat="server" AllowPaging="True" 
            AllowSorting="True" AutoGenerateDeleteColumn="True" 
            AutoGenerateEditColumn="True" CellSpacing="0" 
            DataSourceID="RFPadminDataScource" GridLines="None">
        <ClientSettings AllowColumnsReorder="True" ReorderColumnsOnClient="True">
            <Selecting AllowRowSelect="True" />
        </ClientSettings>
<MasterTableView AutoGenerateColumns="False" DataSourceID="RFPadminDataScource">
<CommandItemSettings ExportToPdfText="Export to PDF"></CommandItemSettings>

<RowIndicatorColumn Visible="True" FilterControlAltText="Filter RowIndicator column">
<HeaderStyle Width="20px"></HeaderStyle>
</RowIndicatorColumn>

<ExpandCollapseColumn Visible="True" FilterControlAltText="Filter ExpandColumn column">
<HeaderStyle Width="20px"></HeaderStyle>
</ExpandCollapseColumn>

    <Columns>
        <telerik:GridBoundColumn DataField="szDirector" 
            FilterControlAltText="Filter szDirector column" HeaderText="szDirector" 
            SortExpression="szDirector" UniqueName="szDirector">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szEmail" 
            FilterControlAltText="Filter szEmail column" HeaderText="szEmail" 
            SortExpression="szEmail" UniqueName="szEmail">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szFax" 
            FilterControlAltText="Filter szFax column" HeaderText="szFax" 
            SortExpression="szFax" UniqueName="szFax">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szPhone" 
            FilterControlAltText="Filter szPhone column" HeaderText="szPhone" 
            SortExpression="szPhone" UniqueName="szPhone">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szHotelPhone" 
            FilterControlAltText="Filter szHotelPhone column" HeaderText="szHotelPhone" 
            SortExpression="szHotelPhone" UniqueName="szHotelPhone">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szTitle" 
            FilterControlAltText="Filter szTitle column" HeaderText="szTitle" 
            SortExpression="szTitle" UniqueName="szTitle">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szName" 
            FilterControlAltText="Filter szName column" HeaderText="szName" 
            SortExpression="szName" UniqueName="szName">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szYear" 
            FilterControlAltText="Filter szYear column" HeaderText="szYear" 
            SortExpression="szYear" UniqueName="szYear">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szRFPID" 
            FilterControlAltText="Filter szRFPID column" HeaderText="szRFPID" 
            SortExpression="szRFPID" UniqueName="szRFPID">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szSabrePropertyNo" 
            FilterControlAltText="Filter szSabrePropertyNo column" 
            HeaderText="szSabrePropertyNo" SortExpression="szSabrePropertyNo" 
            UniqueName="szSabrePropertyNo">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szApolloPropertyNo" 
            FilterControlAltText="Filter szApolloPropertyNo column" 
            HeaderText="szApolloPropertyNo" SortExpression="szApolloPropertyNo" 
            UniqueName="szApolloPropertyNo">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szSabreChainCode" 
            FilterControlAltText="Filter szSabreChainCode column" 
            HeaderText="szSabreChainCode" SortExpression="szSabreChainCode" 
            UniqueName="szSabreChainCode">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szApolloChainCode" 
            FilterControlAltText="Filter szApolloChainCode column" 
            HeaderText="szApolloChainCode" SortExpression="szApolloChainCode" 
            UniqueName="szApolloChainCode">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szHotelName" 
            FilterControlAltText="Filter szHotelName column" HeaderText="szHotelName" 
            SortExpression="szHotelName" UniqueName="szHotelName">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szAddress" 
            FilterControlAltText="Filter szAddress column" HeaderText="szAddress" 
            SortExpression="szAddress" UniqueName="szAddress">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szAddressTwo" 
            FilterControlAltText="Filter szAddressTwo column" HeaderText="szAddressTwo" 
            SortExpression="szAddressTwo" UniqueName="szAddressTwo">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szCity" 
            FilterControlAltText="Filter szCity column" HeaderText="szCity" 
            SortExpression="szCity" UniqueName="szCity">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szState" 
            FilterControlAltText="Filter szState column" HeaderText="szState" 
            SortExpression="szState" UniqueName="szState">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szZipCode" 
            FilterControlAltText="Filter szZipCode column" HeaderText="szZipCode" 
            SortExpression="szZipCode" UniqueName="szZipCode">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szCountry" 
            FilterControlAltText="Filter szCountry column" HeaderText="szCountry" 
            SortExpression="szCountry" UniqueName="szCountry">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szElectronicSig" 
            FilterControlAltText="Filter szElectronicSig column" 
            HeaderText="szElectronicSig" SortExpression="szElectronicSig" 
            UniqueName="szElectronicSig">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szElectronicSigCmt" 
            FilterControlAltText="Filter szElectronicSigCmt column" 
            HeaderText="szElectronicSigCmt" SortExpression="szElectronicSigCmt" 
            UniqueName="szElectronicSigCmt">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="HotelInYear" 
            FilterControlAltText="Filter HotelInYear column" HeaderText="HotelInYear" 
            SortExpression="HotelInYear" UniqueName="HotelInYear">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="dtSTdate" DataType="System.DateTime" 
            FilterControlAltText="Filter dtSTdate column" HeaderText="dtSTdate" 
            SortExpression="dtSTdate" UniqueName="dtSTdate">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="dtEDDate" DataType="System.DateTime" 
            FilterControlAltText="Filter dtEDDate column" HeaderText="dtEDDate" 
            SortExpression="dtEDDate" UniqueName="dtEDDate">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szRmTypeCat" 
            FilterControlAltText="Filter szRmTypeCat column" HeaderText="szRmTypeCat" 
            SortExpression="szRmTypeCat" UniqueName="szRmTypeCat">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="nRmRate" DataType="System.Decimal" 
            FilterControlAltText="Filter nRmRate column" HeaderText="nRmRate" 
            SortExpression="nRmRate" UniqueName="nRmRate">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="lFeatureID" DataType="System.Int32" 
            FilterControlAltText="Filter lFeatureID column" HeaderText="lFeatureID" 
            SortExpression="lFeatureID" UniqueName="lFeatureID">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szPrefHotelName" 
            FilterControlAltText="Filter szPrefHotelName column" 
            HeaderText="szPrefHotelName" SortExpression="szPrefHotelName" 
            UniqueName="szPrefHotelName">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szGeneralMgr" 
            FilterControlAltText="Filter szGeneralMgr column" HeaderText="szGeneralMgr" 
            SortExpression="szGeneralMgr" UniqueName="szGeneralMgr">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szWebSite" 
            FilterControlAltText="Filter szWebSite column" HeaderText="szWebSite" 
            SortExpression="szWebSite" UniqueName="szWebSite">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szDiamondRating" 
            FilterControlAltText="Filter szDiamondRating column" 
            HeaderText="szDiamondRating" SortExpression="szDiamondRating" 
            UniqueName="szDiamondRating">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szStarRating" 
            FilterControlAltText="Filter szStarRating column" HeaderText="szStarRating" 
            SortExpression="szStarRating" UniqueName="szStarRating">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szNegotiatedRate" 
            FilterControlAltText="Filter szNegotiatedRate column" 
            HeaderText="szNegotiatedRate" SortExpression="szNegotiatedRate" 
            UniqueName="szNegotiatedRate">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szDiscountOff" 
            FilterControlAltText="Filter szDiscountOff column" HeaderText="szDiscountOff" 
            SortExpression="szDiscountOff" UniqueName="szDiscountOff">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szLastRoomAvail" 
            FilterControlAltText="Filter szLastRoomAvail column" 
            HeaderText="szLastRoomAvail" SortExpression="szLastRoomAvail" 
            UniqueName="szLastRoomAvail">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szCurrencyCode" 
            FilterControlAltText="Filter szCurrencyCode column" HeaderText="szCurrencyCode" 
            SortExpression="szCurrencyCode" UniqueName="szCurrencyCode">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szVat" 
            FilterControlAltText="Filter szVat column" HeaderText="szVat" 
            SortExpression="szVat" UniqueName="szVat">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szExtendGroupNegRate" 
            FilterControlAltText="Filter szExtendGroupNegRate column" 
            HeaderText="szExtendGroupNegRate" SortExpression="szExtendGroupNegRate" 
            UniqueName="szExtendGroupNegRate">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szConsortiaRate" 
            FilterControlAltText="Filter szConsortiaRate column" 
            HeaderText="szConsortiaRate" SortExpression="szConsortiaRate" 
            UniqueName="szConsortiaRate">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szLowestConsortiaRate" 
            FilterControlAltText="Filter szLowestConsortiaRate column" 
            HeaderText="szLowestConsortiaRate" SortExpression="szLowestConsortiaRate" 
            UniqueName="szLowestConsortiaRate">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szAverageConsortiaRate" 
            FilterControlAltText="Filter szAverageConsortiaRate column" 
            HeaderText="szAverageConsortiaRate" SortExpression="szAverageConsortiaRate" 
            UniqueName="szAverageConsortiaRate">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szHighestConsortiaRate" 
            FilterControlAltText="Filter szHighestConsortiaRate column" 
            HeaderText="szHighestConsortiaRate" SortExpression="szHighestConsortiaRate" 
            UniqueName="szHighestConsortiaRate">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szCorpRate" 
            FilterControlAltText="Filter szCorpRate column" HeaderText="szCorpRate" 
            SortExpression="szCorpRate" UniqueName="szCorpRate">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szRackRate" 
            FilterControlAltText="Filter szRackRate column" HeaderText="szRackRate" 
            SortExpression="szRackRate" UniqueName="szRackRate">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szAsscociationRate" 
            FilterControlAltText="Filter szAsscociationRate column" 
            HeaderText="szAsscociationRate" SortExpression="szAsscociationRate" 
            UniqueName="szAsscociationRate">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szRecruitRatesSeptDec" 
            FilterControlAltText="Filter szRecruitRatesSeptDec column" 
            HeaderText="szRecruitRatesSeptDec" SortExpression="szRecruitRatesSeptDec" 
            UniqueName="szRecruitRatesSeptDec">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szInternetIncRate" 
            FilterControlAltText="Filter szInternetIncRate column" 
            HeaderText="szInternetIncRate" SortExpression="szInternetIncRate" 
            UniqueName="szInternetIncRate">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szRenovations" 
            FilterControlAltText="Filter szRenovations column" HeaderText="szRenovations" 
            SortExpression="szRenovations" UniqueName="szRenovations">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szRenovationsDesc" 
            FilterControlAltText="Filter szRenovationsDesc column" 
            HeaderText="szRenovationsDesc" SortExpression="szRenovationsDesc" 
            UniqueName="szRenovationsDesc">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szRoomCnt" 
            FilterControlAltText="Filter szRoomCnt column" HeaderText="szRoomCnt" 
            SortExpression="szRoomCnt" UniqueName="szRoomCnt">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szSuiteCnt" 
            FilterControlAltText="Filter szSuiteCnt column" HeaderText="szSuiteCnt" 
            SortExpression="szSuiteCnt" UniqueName="szSuiteCnt">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szGuaranteeNotToWalkOurGuests" 
            FilterControlAltText="Filter szGuaranteeNotToWalkOurGuests column" 
            HeaderText="szGuaranteeNotToWalkOurGuests" 
            SortExpression="szGuaranteeNotToWalkOurGuests" 
            UniqueName="szGuaranteeNotToWalkOurGuests">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szHotelGrpAffiliation" 
            FilterControlAltText="Filter szHotelGrpAffiliation column" 
            HeaderText="szHotelGrpAffiliation" SortExpression="szHotelGrpAffiliation" 
            UniqueName="szHotelGrpAffiliation">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szEnvCertPrg" 
            FilterControlAltText="Filter szEnvCertPrg column" HeaderText="szEnvCertPrg" 
            SortExpression="szEnvCertPrg" UniqueName="szEnvCertPrg">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szRecyclingPrg" 
            FilterControlAltText="Filter szRecyclingPrg column" HeaderText="szRecyclingPrg" 
            SortExpression="szRecyclingPrg" UniqueName="szRecyclingPrg">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szUtilEnvRespCleaners" 
            FilterControlAltText="Filter szUtilEnvRespCleaners column" 
            HeaderText="szUtilEnvRespCleaners" SortExpression="szUtilEnvRespCleaners" 
            UniqueName="szUtilEnvRespCleaners">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szActiveWaterCnsvPrg" 
            FilterControlAltText="Filter szActiveWaterCnsvPrg column" 
            HeaderText="szActiveWaterCnsvPrg" SortExpression="szActiveWaterCnsvPrg" 
            UniqueName="szActiveWaterCnsvPrg">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szIncentive" 
            FilterControlAltText="Filter szIncentive column" HeaderText="szIncentive" 
            SortExpression="szIncentive" UniqueName="szIncentive">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szAmenitiesIncluded" 
            FilterControlAltText="Filter szAmenitiesIncluded column" 
            HeaderText="szAmenitiesIncluded" SortExpression="szAmenitiesIncluded" 
            UniqueName="szAmenitiesIncluded">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szIsPropVirtuosoMem" 
            FilterControlAltText="Filter szIsPropVirtuosoMem column" 
            HeaderText="szIsPropVirtuosoMem" SortExpression="szIsPropVirtuosoMem" 
            UniqueName="szIsPropVirtuosoMem">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szVirtuosoAmmen" 
            FilterControlAltText="Filter szVirtuosoAmmen column" 
            HeaderText="szVirtuosoAmmen" SortExpression="szVirtuosoAmmen" 
            UniqueName="szVirtuosoAmmen">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szIsVirtuosoAmmenInc" 
            FilterControlAltText="Filter szIsVirtuosoAmmenInc column" 
            HeaderText="szIsVirtuosoAmmenInc" SortExpression="szIsVirtuosoAmmenInc" 
            UniqueName="szIsVirtuosoAmmenInc">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szEnsureAmenty" 
            FilterControlAltText="Filter szEnsureAmenty column" HeaderText="szEnsureAmenty" 
            SortExpression="szEnsureAmenty" UniqueName="szEnsureAmenty">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szGuestRoom" 
            FilterControlAltText="Filter szGuestRoom column" HeaderText="szGuestRoom" 
            SortExpression="szGuestRoom" UniqueName="szGuestRoom">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szPublicSpace" 
            FilterControlAltText="Filter szPublicSpace column" HeaderText="szPublicSpace" 
            SortExpression="szPublicSpace" UniqueName="szPublicSpace">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szITinPublicSpaceInc" 
            FilterControlAltText="Filter szITinPublicSpaceInc column" 
            HeaderText="szITinPublicSpaceInc" SortExpression="szITinPublicSpaceInc" 
            UniqueName="szITinPublicSpaceInc">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szItinGuestRoomInc" 
            FilterControlAltText="Filter szItinGuestRoomInc column" 
            HeaderText="szItinGuestRoomInc" SortExpression="szItinGuestRoomInc" 
            UniqueName="szItinGuestRoomInc">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szHotelDesc" 
            FilterControlAltText="Filter szHotelDesc column" HeaderText="szHotelDesc" 
            SortExpression="szHotelDesc" UniqueName="szHotelDesc">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szRestaurant" 
            FilterControlAltText="Filter szRestaurant column" HeaderText="szRestaurant" 
            SortExpression="szRestaurant" UniqueName="szRestaurant">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szBarLounge" 
            FilterControlAltText="Filter szBarLounge column" HeaderText="szBarLounge" 
            SortExpression="szBarLounge" UniqueName="szBarLounge">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szToiletries" 
            FilterControlAltText="Filter szToiletries column" HeaderText="szToiletries" 
            SortExpression="szToiletries" UniqueName="szToiletries">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szModifierID" 
            FilterControlAltText="Filter szModifierID column" HeaderText="szModifierID" 
            SortExpression="szModifierID" UniqueName="szModifierID">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szNegRate" 
            FilterControlAltText="Filter szNegRate column" HeaderText="szNegRate" 
            SortExpression="szNegRate" UniqueName="szNegRate">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="szDirectorOfSales" 
            FilterControlAltText="Filter szDirectorOfSales column" 
            HeaderText="szDirectorOfSales" SortExpression="szDirectorOfSales" 
            UniqueName="szDirectorOfSales">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="UserRFPID" 
            FilterControlAltText="Filter UserRFPID column" HeaderText="UserRFPID" 
            SortExpression="UserRFPID" UniqueName="UserRFPID">
        </telerik:GridBoundColumn>
    </Columns>

<EditFormSettings>
<EditColumn FilterControlAltText="Filter EditCommandColumn column"></EditColumn>
</EditFormSettings>
</MasterTableView>

<FilterMenu EnableImageSprites="False"></FilterMenu>
</telerik:RadGrid>
        <asp:SqlDataSource ID="RFPadminDataScource" runat="server" 
            ConnectionString="Data Source=NYC-HQSQL-08;Initial Catalog=BetaOvation4;Persist Security Info=True;User ID=OvationClient;Password=OvationClient-sql-08" 
            ProviderName="System.Data.SqlClient" 
            SelectCommand="SELECT        Tbl_Hotel_PHC_HotelInfoPartialOne.szSabrePropertyNo, Tbl_Hotel_PHC_HotelInfoPartialOne.szApolloPropertyNo, 
                         Tbl_Hotel_PHC_HotelInfoPartialOne.szSabreChainCode, Tbl_Hotel_PHC_HotelInfoPartialOne.szApolloChainCode, Tbl_Hotel_PHC_HotelInfoPartialOne.szHotelName, 
                         Tbl_Hotel_PHC_HotelInfoPartialOne.szAddress, Tbl_Hotel_PHC_HotelInfoPartialOne.szAddressTwo, Tbl_Hotel_PHC_HotelInfoPartialOne.szCity, 
                         Tbl_Hotel_PHC_HotelInfoPartialOne.szState, Tbl_Hotel_PHC_HotelInfoPartialOne.szZipCode, Tbl_Hotel_PHC_HotelInfoPartialOne.szCountry, 
                         Tbl_Hotel_PHC_HotelInfoPartialOne.szElectronicSig, Tbl_Hotel_PHC_HotelInfoPartialOne.szElectronicSigCmt, Tbl_Hotel_PHC_RFP_Related_User.szRFPID
FROM            Tbl_Hotel_PHC_RFP_Related_User INNER JOIN
                         Tbl_Hotel_PHC_HotelInfoPartialOne ON Tbl_Hotel_PHC_RFP_Related_User.szRFPID = Tbl_Hotel_PHC_HotelInfoPartialOne.szRFPID">
        </asp:SqlDataSource>
    </div>
    </form>
</body>
</html>

